### ISSUE TITLE
CollectUI CodeConventions

### ISSUE THREAD

**Issue by wesselvink** [Gijs-schouten/ProeveVanBekwaamheid#47]
in [CollectUI](https://github.com/Gijs-schouten/ProeveVanBekwaamheid/blob/master/Assets/Scripts/Collectable/CollectUI.cs) gebruik je bij _collected wel de code conventions maar niet bij de player

**Comment by wesselvink** [comment]
Bij [Healt.cs](https://github.com/Gijs-schouten/ProeveVanBekwaamheid/blob/master/Assets/Scripts/Health/Health.cs) bij de eerste private variabelen gebruik je wel de code conventions, maar bij de 2e niet?

**Comment by BorahanO** [comment]
Fixed in latest commit
