### ISSUE TITLE
PlayerMovement.cs

### ISSUE THREAD

**Issue by Gijs-schouten** [Gijs-schouten/ProeveVanBekwaamheid#51]
Je flipt [hier](https://github.com/Gijs-schouten/ProeveVanBekwaamheid/blob/master/Assets/Scripts/Character/PlayerMovement.cs) de sprite met scale maar SpriteRenderer heeft een FlipX en FlipY bool.

**Comment by wesselvink** [comment]
Aangezien we 3 layers van de player sprites hebben moet ik ze alle 3 flippen. Nu flip ik de parent waardoor alles te gelijkertijd mee draait
