### ISSUE TITLE
ActivateObject.cs Pascal Casing?

### ISSUE THREAD

**Issue by wesselvink** [Gijs-schouten/ProeveVanBekwaamheid#53]
bij [ActivateObject.cs](https://github.com/Gijs-schouten/ProeveVanBekwaamheid/blob/master/Assets/Scripts/UI/ActivateObject.cs) maak je ineens gebruik van Pascal Casing voor variabelen

**Comment by Gijs-schouten** [comment]
Heb het aangepast.
